# Generated by Django 5.2.1 on 2025-05-20 22:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_start', models.FloatField()),
                ('lat_start', models.FloatField()),
                ('long_end', models.FloatField()),
                ('lat_end', models.FloatField()),
                ('length', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SpeedReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('road_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speed_readings', to='roads.roadsegment')),
            ],
        ),
    ]
