# Generated by Django 5.2.1 on 2025-05-21 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadsegment',
            name='name',
            field=models.CharField(blank=True, help_text="Unique sensor name (e.g., 'noisy-panda')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='speedreading',
            name='road_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='speed_readings', to='roads.roadsegment'),
        ),
        migrations.AddConstraint(
            model_name='roadsegment',
            constraint=models.UniqueConstraint(fields=('lat_start', 'long_start', 'lat_end', 'long_end'), name='unique_roadsegment_coordinates'),
        ),
    ]
