# Generated by Django 5.2.1 on 2025-05-21 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0002_roadsegment_name_alter_speedreading_road_segment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speedreading',
            name='timestamp',
        ),
    ]
