# Generated by Django 5.2.1 on 2025-05-22 11:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roads", "0004_remove_roadsegment_unique_roadsegment_coordinates_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="speedreading",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
